export const CST = {
    SCENES: {
        LOAD: "LOAD",
        MENU: "MENU",
        LEVELONE: "LEVELONE",
        OPTIONS: "OPTIONS",
        LEVELTWO: "LEVELTWO",
        LEVELONEMODERN: "LEVELONEMODERN",
        LEVELTWOMODERN: "LEVELTWOMODERN",
        LEVELTHREE: "LEVELTHREE",
        LEVELTHREEMODERN: "LEVELTHREEMODERN",
    },
};
